aliya-rahmani/Projects

Tic-Tac-Toe.py
new game added - Tic Tac Toe game in Python
=> new game added

treasure_of_ocean.py
This has been done because of the issue #1 of Code_for_hacktoberfest in afred-khan Repository!
=> Added a game TREASURE_OF_OCEAN.PY!

group_anagram.py
Added group _ anagram program. The problem description is given in the file itself
=> Added group_anagram

C++/AStar.cpp, C++/Bubble_Sorting.cpp, C++/Bucket Sort.cpp, C++/Counting_Sort.cpp, C++/HeapSort.cpp, C++/Jump_Search.cpp, C++/README.md, C++/Radix Sort.cpp, C++/mergeSort.cpp, C++/quickSort.cpp
=> added C++ Programs

Number_Guessing_Game.py
A number guessing game using GUI Tkinter.
=> Added Number_Guessing_Game.py

Projectile_Motion_Game.py
User can perform projectile motion with the help of the ball.
=> Added program to make projectile motion game

Foreground_and_Background_Extraction.py
fg - foreground
bg - background
=> Added program to perform fg and bg extraction

Text-Based-Adventure-Quiz-Game.py
=> Added Text-Based-Adventure-Quiz-Game.py

C++/BSF.cpp, C++/Tower_of_hanoi.cpp, C++/bellmanford.cpp
issue number - #3 
c++ codes added.
=> Added c+ codes of some important algorithms

Java/DoublyLinkedList.java, Java/SelectionSort.java, Java/SinglyLinkedList.java
=> Adding more Java resources

C++/InsertionSort.cpp, C++/SelectionSort.cpp, C++/TimSort.cpp, C/BogoSort.c, C/BucketSort.c, C/CombSort.c, C/CountingSort.c, C/HeapSort.c, C/InsertionSort.c, C/MergeSort.c, C/QuickSort.c, C/RadixSort.c, C/SelectionSort.c, C/ShellSort.c, C/cycleSort.c, Java/BitonicSort.java, Java/BogoSort.java, Java/BucketSort.java, Java/HeapSort.java, Java/TimSort.java, number_guessing_game.py
New Sorting algorithms added for language C, C++ and Java
**C++**
Insertion Sort
Selection Sort
Tim Sort
**C**
Bogo Sort
Bucket Sort
Comb Sort
Counting Sort
Cycle Sort
Heap Sort
Insertion Sort
Merge Sort
Quick Sort
Radix Sort
Sekection Sort
Shell Sort
**Java**
Bitonic Sort
Bogo Sort
Bucket Sort
Heap Sort
Tim Sort
=> New Sorting algorithms added for language C, C++ and Java

Rock Paper Scissors.py
A game of Rock Paper Scissors made in Python using tkinter to Play against A computer.
=> Rock Paper Scissors Game in python

Python/Rock, Paper And Scissor_Cheating Not Allowed/Rock_paper_and_scissor-cheating_not_allowed.py
=> Rock, Paper And Scissor Game

C#/PalindromeChecker.cs
Added a palindrome checking console program in c#
#4
=> Added PalindromeChecker in C#

Leap Year Checker
A program that tells you whether given a year is a leap year or not.
=> Leap year checker in Python

BinarySearch.py
Profram for Binary Search using Python
=> Binary Search using Python

Python/stopwatch.py
stopwatch in python programming
=> stopwatch.py

Email Sender.py
=> Email Sender in Python

HTML/SIGN UP.html
- I saw that there was no folder for any HTML
- Hence made a folder for Html and added a program for a **SIGN UP** page made by me.
=> Made a **new folder for HTML pages**

C#/Simple2DAstarImplemtation.cs
Adds a simple A* system to the C# section
=> A simple A* implementation in C#

C/BinarySearchTree.c
Added Binary Search tree in C
C/BinarySearchTree.c
#4
=> Added Binary Search tree in C

Color Game.py
In this game, the player has to enter the color of the word that appears on the screen, and hence the score increases by one, the total time to play this game is 1 minute. Interface will display name of different colors in different colors. Player has to identify the color and enter the correct color name to win the game.
=> Color Game in Python

C++/segment_tree.cpp
Added segement tree implementation using lazy propagation in cpp and using stl support
=> Added segement tree implementation using lazy propagation in cpp

C++/bridges_in_graph.cpp, C++/segment_tree.cpp
bidirectional to unidirectional graph conversion using bridges and articulation point concept using cpp and dfs in and out time concept.
=> bidirectional to unidirectional graph conversion using bridges and articulation point concept

Python/Factorial_DP.py
Factorial program in python, using dynamic programming to store previously calculated sub problems using a memoization array.
following issue #2
=> Factorial program with dynamic programming

Calculator.py
It is a simple calculator made using tkinter in python
=> Calculator made in python

Python/FindMinPath.py
I added a file called FindMinPath.py 
Given a File Path as a command line argument that holds a Matrix where each element is separated by a , and each row by \n and where each space is given a certain weight I would like to find the how to get from upper left corner to the bottom right corner using the lightest weight as possible 
this solves problem #130
=> Finds Min path in a Matrix 

Python/massIndex.py
=> Mass index function in python

Python/alert/alert.py, Python/alert/keywords.json
Added python project to search for specific words(specified in keywords.json) in files inside a given directory.
=> added keyword searcher python project

Java/calculator.java, Java/factorial.java, Java/fibonacci.java, Java/primeCheck.java, Java/swapTwoNumbers.java
added fibonacci.java, factorial.java, calculator.java, swapTwoNumbers.java and primeCheck.java
=> uploaded 5 java programs

C++/Saddle Point in 2D Array.cpp
@afred-khan please check and merge Saddle Point in 2D Array in C++ language
=> Add Saddle Point in 2D Array code in C++

C++/Fibonacci series using Binet's Theorem.cpp
@afred-khan  please check and merge code of Fibonacci series using Binet's Theorem in C++ language
=> Add Fibonacci series using Binet's Theorem code in C++

C++/Equilibrium Point in Array.cpp
@afred-khan please check and merge code of Equilibrium Point in Array
=> Add Equilibrium Point in Array in C++ language

Rust/CALCULATOR.rs
@afred-khan please check and merge calculator program in rust language.
=> Add calculator program in Rust Language

C++/Linear search.cpp
@afred-khan please check and merge the code of linear search
=> add linear search code in c++ language

Computer Vision/Vehicle-detection/program.py, Computer Vision/Vehicle-detection/required_haarCascade.xml
Added Demo python program for Vehicle detection using OpenCV
Please add this for Hacktoberfest 2020
Thank You
=> Computer Vision/vehicle detection using OpenCV

Python/TESLA.py
This program monitors the share price of a specific stock, in this case, Tesla. It then sends an email to the person to notify him when the share price is beyond a particular limit.
I used the Selenium as well as Yagmail libraries.
=> ADDED program to monitor share prices

Java/PigeonHoleSort.java
Added PigeonHoleSort.java to HacktoberFest/Java
For issue #4
=> Added PigeonHoleSort.java to HacktoberFest/Java

Python/.idea/Python.iml, Python/.idea/inspectionProfiles/profiles_settings.xml, Python/.idea/modules.xml, Python/.idea/vcs.xml, Python/.idea/workspace.xml, Python/GUI-CHATBOX/client side.py, Python/GUI-CHATBOX/server side.py, Python/GUI-Calculator.py, Python/GUI_MUSIC PLAYER/GUI MUSIC PLAYER.py, Python/GUI_MUSIC PLAYER/Readme.txt, Python/INSTAGRAM IMAGE DOWNLOADER/Insta Image Downloader.py, Python/INSTAGRAM IMAGE DOWNLOADER/Readme.txt
Added Instagram Image Downloader
=> Instagram Image Downloader

Python/.idea/Python.iml, Python/.idea/inspectionProfiles/profiles_settings.xml, Python/.idea/modules.xml, Python/.idea/vcs.xml, Python/.idea/workspace.xml, Python/GUI-CHATBOX/client side.py, Python/GUI-CHATBOX/server side.py, Python/GUI-Calculator.py, Python/GUI_MUSIC PLAYER/GUI MUSIC PLAYER.py, Python/GUI_MUSIC PLAYER/Readme.txt
=> GUI based Music Player

Python/.idea/Python.iml, Python/.idea/inspectionProfiles/profiles_settings.xml, Python/.idea/modules.xml, Python/.idea/vcs.xml, Python/.idea/workspace.xml, Python/GUI-CHATBOX/client side.py, Python/GUI-CHATBOX/server side.py, Python/GUI-Calculator.py
Added GUI based Chat box using tinker
Added GUI based Calculator using tinker
=> GUI based Chat box & GUI based Calculator using tinker

C++/fibonacci_recursive.cpp
=> Created fibonacci series using recursion in C++

ArrayRotation.java
rotates an array that is changes position by one place.
=> ArrayRotation.java

C/stopwatch.c
stopwatch program in c language  it is a simple program to understand the c programming
=> stopwatch.c

Python/.idea/Python.iml, Python/.idea/inspectionProfiles/profiles_settings.xml, Python/.idea/modules.xml, Python/.idea/vcs.xml, Python/.idea/workspace.xml, Python/GUI-CHATBOX/client side.py, Python/GUI-CHATBOX/server side.py, Python/GUI-CURRENCY CONVERTER/GUI-CURRENCY CONVERTER.py, Python/GUI-CURRENCY CONVERTER/Readme.txt, Python/GUI-Calculator.py, Python/GUI_MUSIC PLAYER/GUI MUSIC PLAYER.py, Python/GUI_MUSIC PLAYER/Readme.txt, Python/INSTAGRAM IMAGE DOWNLOADER/Insta Image Downloader.py, Python/INSTAGRAM IMAGE DOWNLOADER/Readme.txt
=> Currency Converter

Python/.idea/Python.iml, Python/.idea/inspectionProfiles/profiles_settings.xml, Python/.idea/modules.xml, Python/.idea/vcs.xml, Python/.idea/workspace.xml, Python/ALARM CLOCK/ALARM CLOCK.py, Python/ALARM CLOCK/Readme.txt, Python/GUI-CHATBOX/client side.py, Python/GUI-CHATBOX/server side.py, Python/GUI-CURRENCY CONVERTER/GUI-CURRENCY CONVERTER.py, Python/GUI-CURRENCY CONVERTER/Readme.txt, Python/GUI-Calculator.py, Python/GUI_MUSIC PLAYER/GUI MUSIC PLAYER.py, Python/GUI_MUSIC PLAYER/Readme.txt, Python/INSTAGRAM IMAGE DOWNLOADER/Insta Image Downloader.py, Python/INSTAGRAM IMAGE DOWNLOADER/Readme.txt
=> Alarm Clock in Python

C++/AVL_Tree.cpp
Implementation of AVL Tree in cpp
=> Added AVL_Tree.cpp

pokemon.py
this program asks the user for their favourite pokemon and returns a poke card (img) with that pokemon's real time stats
=> created pokemon.py

C++/AVL_Tree.cpp, C++/Closest_pair_of_points.cpp, C++/Euler_Totient_Function.cpp, C++/Longest_Common_Subsequence.cpp
This is an algorithm of Computational Geometry which aims at finding distance between closest pair of points among n given points.
=> Added Closest_pair_of_points.cpp

C++/AVL_Tree.cpp, C++/Longest_Common_Subsequence.cpp
Implementation of Longest Common Subsequence in cpp using Dynamic Programming.
=> Added Longest_Common_Subsequence.cpp

C++/AVL_Tree.cpp, C++/Euler_Totient_Function.cpp, C++/Longest_Common_Subsequence.cpp
Implementation of Euler Totient Function in cpp
=> Added Euler_Totient_Function.cpp

C++/Singly_Linked_List.cpp
For issue #3 .
'Singly_Linked_List.cpp'-A program to perform insertion and deletion at head ,middle and tail elements respectively. Implemented in C++.
=> Added a singly Linked List Program

HTML/calendar.html
This a calendar presentation in HTML5 . Added in the folder HTML .Please review .
@afred-khan
=> Added a Calendar in HTML

Python/BinarySearchTree.py
Added Binary Search Tree Implementation in Python
Python/BinarySearchTree.py
=> Added BST Implementation in Python

Python/gui-calculator/calculator.py, Python/gui-calculator/style.css
this is a gui calculator made with python and pyqt5. it has a bit polished UI and functions decently well.
=> added gui calculator project written in python

Python/Hangman.py
It's just a basic Hangman avengers edition!!
=> Hangman written in python

.idea/-HACKTOBERFEST2K20.iml, .idea/.gitignore, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, Python/8Ball.py
8 ball game 
Features:
Generates number which then presents an answer to a question
=> Added 8 ball game

C++/Binary Search.cpp
@afred-khan please check and merge the code of binary search
=> Add the binary search code in C++

Java/MakingAnagrams.java, Java/README.md
Please add the label hacktoberfest2020 and merge it in your repo
=> Added Making Anagrams in Java

C/single_linklist_concatenation.c, C/singly_linked_list.c
singly_linked_list.c
1. It includes all the operation likes addition of nodes from link list
2. It includes all the operation likes deletion of nodes from link list
single_linklist_concatenation.c
1. It includes concatenation operation on a link list
=> Added programs related to link list in C folder

Face_Detection/Face_detection_Code/Face Detect.py, Face_Detection/Face_detection_Code/Requirement.txt, Face_Detection/Face_detection_Code/haarcascade_frontalface_default.xml
Python program for Face Detection using OpenCV and Haarcascade
=> Face Detection using OpenCV and Haarcascade

website_blocker.py
Add a python program used to block websites from a list
=> Add website_blocker.py

QuickSort.py
Added QuickSort.py which includes an implementation of quicksort algorithm
=> Add Quicksort algorithm in python

C++/Binary_search.cpp, C++/LIS.cpp
=> add approach for longest increase subsequence using dynamic programming

C++/isomorphic_binary_trees.cpp
This PR adds a new algorithm written on C++ to check whether two given binary trees are isomorphic.
=> Add: CPP Isomorphic Trees

Python/coviid-19.ipynb
just added a Dashboard in **jupyter-notebook** for COVID rate in **INDIA** (state-wise)
=> Added Covid Dashboard for INDIA STATE-WISE

C/Matrix Operations/Matrix Operations.c, Python/Regex Search/Regex_search.py
Menu-driven program to perform operations on the matrix-like addition, subtraction, multiplication, greatest number from each row, the addition of major diagonal elements and the sparse matrix representation of the given matrix
=> Matrix operations

Python/Regex Search/Regex_search.py
CodeChef Problem Solving (https://www.codechef.com/problems/ERROR)
=> Regex Search

flipkart-price-alert/README.md, flipkart-price-alert/config.py, flipkart-price-alert/requirements.txt, flipkart-price-alert/track.py
Tracks and alerts (via email) about price changes of your desired product on flipkart.com
=> Added flipkart.com price alert

Python/Discount_calc.py
Just did my part of the contribution in this really well-organized repository.Hoping for the best!
=> Added a discount calculator 

C/Pancake_Sort.c
=> Pancake_Sort.c

Java/IntToRoman.java
=> Added algorithm for Integer numbers to Roman numerals conversion

C++/AdHoc/leap_year.cpp, C++/AdHoc/spiral_print.cpp, C++/AdHoc/tokenizer.cpp, C++/Math/FastPower.cpp, C++/Math/ModularArithmetic.md, C++/Math/MultipleInRange.md, C++/Math/binomial_coefficient.cpp, C++/Math/catalan_number_dynamic.cpp, C++/Math/fermats_little_theorem.cpp, C++/Math/modular_inverse.cpp, C++/Math/prime_factors.cpp, C++/Math/prime_numbers_of_n.cpp, C++/Math/print_divisors.cpp, C++/Math/segmented_sieve_of_eratosthenes.cpp, C++/Math/sieve_of_eratosthenes.cpp, C++/Math/tower_of_hanoi.cpp, C++/Math/tribonacci_numbers.cpp
Adding some C++ adhoc and math codes
=> [ADD] C++: AdHoc, Math

simple_calculator.py
A simple GUI calculator using tkinter module in python.
A simple fun project.
=> Added simple_calculator

C++/Doubly_Linked_List.cpp
Issue #3 .'Doubly_Linked_List.cpp'-A program to perform insertion and deletion at head ,middle and tail elements respectively. Implemented in C++.
=> Added a doubly linked list program

C++/main.cpp
=> All Binary Tree Operations

C++/main.cpp
=> Threaded binary tree

C++/main.cpp, Python/karatsuba-mul.py
=> Karatsuba multiplication

C++/main.cpp, Python/karatsuba-mul.py, Python/selection_sort.py, selection_sort.py
=> Selection sort

drive_list.py
=> Drive List

C++/Pancake Sort.cpp
@afred-khan please check and merge Pancake sort code in C++ language
=> Add Pancake Sort code in c++ language

C++/Primechecker.cpp
@afred-khan please check and merge prime checker code in c++ language
=> Add prime checker code in c++ language

C++/subset_sum.cpp
=> added subset sum probelm DP

C++/Fibonacci_Series_Using_Recursion.cpp
Please check i made a c++ program of fibonacci series and added in the c++ folder
=>  Add the fibonacci series in c++ folder

C++/Priorityqueue.cpp
=> Added C++ code of priority queue using recursion

Ruby/BubbleSort.rb
I added a new folder to put some algorithms in ruby
=> first code in Ruby

TicTacToe game in C++/TicTacToe.cpp
I have created a game Tic Tac Toe which we can play against computer. Please merge my pull request
=> added tictactoe game against computer

Java/MatrixMultiply.java
Objective of the code
1. Code takes two Matrix one by one from the user
2. It then does Matrix Multiplication operation on Matrix and stores it in new Matrix
3. It finally displays the Multiplication of inputed Matrix
=> Program for Matrix Multiplication

detect_blinks.py
Implemented Eye Blink Detector using Python and OpenCV. This references issue #2 . Please review and merge @afred-khan
=> Blink Detector using Python and Computer Vision

EnglishDictionary/dictionary.py
This is a python program that can be used as a dictionary.
=> Add dictionary program

Java/stopwatch.java
I can add a stopwatch program in the java folder this is a GUI program in java programming
=> stopwatch.java

C#/bubblesort.cs
I can add a bubbles sort program in the c# folder this is a simple program to know the bubble sort in c# language
=> bubblesort.cs

Ruby/heap_sort.rb
=> Add heap sort ruby

Convert Kilometers to Miles
Python Program to Convert Kilometers to Miles
=>  Kilometers to Miles

C++/Kadane.cpp
I have added kadane's algorithm to c++ folder. Please merge this pull request.
#3
=> Kadane algorithm added

SET Operations
Program for different SET operations
=> SET Operations

Add Matrix, Cube Of N Numbers using Python, Find N number of Fibonacci, Transpose of A matrix
=> python program to add matrices 

Java/DesignHashSet.java, Java/README.md
Problem Link : https://leetcode.com/problems/design-hashset/
Designed a HashSet Library without using the built-in HashSet library in Java.
Please assign the "hacktober-accepted" label and merge it.
=> Added Design HashSet Problem in Java

To-Do Application in JS/README.md, To-Do Application in JS/Tweets.css, To-Do Application in JS/Tweets.html
Adding a To-Do application made using HTML,CSS & JavaScript.
- It can add to-do's and has option to delete them
=> Adding To-do web app

Python/bogosort.py
Added a python implementation of the bogosort sorting algorithm
=> Added bogosort sorting algorithm

Form Validation/README.md, Form Validation/index.html, Form Validation/main.js
This code has a form which has javascript validation
=> Form validation with javascript

Python/Console_Race_Game.py
A luck base Racing Game on console
=> Sudhanshu1304 race game

Python/Console_Race_Game.py, Python/NUERAL_NETWORK.py
Neural Network without libraries
=> Neural network

Python/Bak_Elimination.py, Python/Console_Race_Game.py
=> Back elimination

Python/Notepad GUI.py
It is a program made in Tkinter to make a notepad using Python.
=> Notepad GUI

Python/pcInformationShow.py, Python/stack.py
you need first to install (psutil) library with pip
=> show information of your machine in command line.

Python/maximumEdgeOfTriangle.py
Added maximumEdgeOfTriangle.py for calculating the maximum length of third edge of a triangle.
=> Added maximumEdgeOfTriangle in Python

C++/equal_sum_partition.cpp
Added equal sum partition algo using DP top down approach.
=> added equal sum partition algo using DP

problems of c++
=> competitve problems of c++

Python/Console_Race_Game.py, Python/Multicoliniarity_ML.py
These Algo USES VIR to finds Multicollinearity
=> Sudhanshu1304 multicoliniarity

C++/Shopping_List.cpp, Python/Notepad GUI.py
A simple program to create a shopping list in CPP.
=> Shopping List

C++/Base_conversion.cpp, Python/Notepad GUI.py
Convert every type of base conversion in CPP.
=> Base Conversion

C++/Fractional Knapsack.cpp
@afred-khan please check and merge the fractional knapsack code in c++ language
=> Add Fractional Knapsack Code in c++ language

Python/Display Letters using Raspberry/letras.py, Python/Display Letters using Raspberry/main.py
This Script have the Raspberry Pins setup to turn on leds on a 16x16 display.
=> Display letters using an raspberry pi3

C/Stack-DataStructure/stack.c
I have made a little contribution in this project. That is :
1. Insert 
2. Delete(pop) 
3. Traverse(display)
4. Peak(top_element)
5. Length ...etc
Thank You ...
=> Uploaded stack data structure Implementation in C

Python/Quadratic_equation.py
=> Quadratic equation

merge_sort.py
Hey, check this implementation in python.
=> merge_sort.py

NumPalindrome.py
=> add Palindrome Number file

Go/selection_sort.go
Add selection sort in go.
More about selection sort please refer to [Selection Sort](https://en.wikipedia.org/wiki/Selection_sort)
Thanks 😊 😊
=> Add selection sort in Go

Java/Alternate_Rotation_Of_Matrix_LayerByLayer_By_K_Places.java, Java/IsPrime.java, Java/Permutation.java, Java/gcd.java, Java/pow.java
IsPrime.java : It checks the prime numbers from 1 to n using Sieve method.
gcd : Very Optimal solution of finding gcd.
pow : Optimal Solution of finding power with mod when value crosses 1e7.
=> Few Java Programs.

Go/insertion_sort.go, Go/selection_sort.go
Add Insertion sort in go.
More about selection sort please refer to [Insertion Sort](https://en.wikipedia.org/wiki/Insertion_sort)
Thanks 😊 😊
=> Add Insertion Sort in Go

Java/lcs.java, edge.py
simple edge  detector using opencv lib
=> Added Edge detector 

C/insertElementSortedArray.c
Uploaded C programme for Insert A New Element in Correct Position of A Sorted Array...
=> Uploaded C programme for Insert A New Element in a Sorted Array.

Rust/Binary Search.rs
=> add binary search code

Python/Algorithms/insertin_sort.py, Python/Algorithms/selection_sort.py
=> Moved Algorithm to python folder

Go/shell_sort.go
Add Shell Sort in Go
More about selection sort please refer to [Shell Sort](https://en.wikipedia.org/wiki/Shellsort)
Thank You 😊😊
=> Add Shell Sort in Go

Go/merge_sort.go, Go/shell_sort.go
Add merge sort in go
More about merge sort please refer to [Merge Sort](https://en.wikipedia.org/wiki/Merge_sort)
=> Add merge sort in Go

merge_sort.js
This PR has code for merge sort in javascript. Please review the PR.
=> Sorting in javascript #132

Ruby/BinarySearch.rb, Ruby/SimpleCalculator.rb
Just added a binary search and a simple calculator :D
=> add more ruby code

Rust/Prime number.rs
=> prime number code

Rust/Kadane's Algorithm.rs
=> Kadane algorithm in rust language

Python/animation_of_ILoveU.py
While maintaining the hard-encoding  work of the characters :)
=> Making the functions work in pythonist way =)

Python/Reddit/README.md, Python/Reddit/Reddit Posts Grabber.py
A python script that grabs upto 100 top posts from any subreddit.
=> Added Reddit Posts Grabber in Python

Python/Rock_paper-scissor/paper.py, Python/Rock_paper-scissor/utils.py
Hey, I added a Rock Paper Scissor Game i made in python.
I am just starting out with programming and github that is why such a basic project.
=> Added Rock Paper Scissor Game

ps3_hangman.py
Python game of scrambled strings : Hangman Game.
=> Hangman Game

HTML/countdown.html
This file have a JS snippet with HTML with a countdown that begins on the actual time to the stipuladed date.
=> Create the countdown.html file

Python/RockPaperScissor game.py
Fun game to play rock paper scissors
=> RockPaperScissors.py

pokemon.html
A simple HTML webpage made for practicing tables.
=> Add pokemon.html

Python/mad-libs.py
It's a really funny game where paragraphs which make no sense are randomly generated.
=> added a mad-libs generator game in Python folder

C++/Greedy/fractional_knapsack.cpp
For issue #3 
Fractional kanpsack problem solution
=> Added greedy algorithm for fractional knapsack

Python/Socket Programming/Async_socket_read_and_write/Sender.py, Python/Socket Programming/Async_socket_read_and_write/display.py, Python/Socket Programming/Async_socket_read_and_write/prompter.py
Added a example of how to use a socket object as both receiver and sender in P2P network. 
Please consider for hactoberfest
Thanks
=> Socket programming in python

Python/exponent.py
=> Added Exponent.py

Java/Bellmann_Ford.java, Java/ShortestCommonSupersequence.java
=> added bellmann_ford and shortestCommonSuperSquence algorithms in java

Python/debt_calculator.py, Python/money_calculator.py
Solving this issue https://github.com/afred-khan/-HACKTOBERFEST2K20/issues/1
=> Debt calculator in python

C#/Fibonacci
=> Tried Fibonacci

Python/Algorithms/BubbleSort.py
Simplified the number of lines of code.
=> Updated Bubble Sort.py

Python/Algorithms/selection_sort.py
Added a test case to the code.
=> Updated Selection Sort.py

Python/Algorithms/insertin_sort.py
Added a test case to the code.
=> Updated Insertion Sort.py

Python/Algorithms/MergeSort.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#439
=> Revert "Updated Merge Sort.py"

Python/Algorithms/insertin_sort.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#431
=> Revert "Updated Insertion Sort.py"

javascript/scroll-to-item-example/index.html, javascript/scroll-to-item-example/scroll-to-item.js, javascript/scroll-to-item-example/style.css
- Scroll to specific item in a list using scrollIntoView method
=> Add scroll to item JS example

C++/DataStructure/Stack.cpp
Program For Stack Implementation
=> Stack Implementation

C/MAXIMUM CIRCULAR SUBARRAY SUM.c
I have added a solution code in C language to find maximum subarray sum in circular array.
=> Create MAXIMUM CIRCULAR SUBARRAY SUM.c

javascript/infinite-scroll/index.html, javascript/infinite-scroll/infinite-scroll.js, javascript/infinite-scroll/style.css
- Add example for make an infinite scroll in Javascript
=> Add infinite-scroll example

Java/Complex_Number.java
Contributing for HacktoberFest 2020
=> Complex Numbers program in java

betweentwosetsthecommonfactors.py, minimumsumoffactors.py
minimum sum of the factors of a  number.
=> minimumsumoffactors.py

Python/Algorithms/selection_sort.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#430
=> Revert "Updated Selection Sort.py"

Java/stopwatch.java
Reverts aliya-rahmani/-HACKTOBERFEST2K20#414
=> Revert "Update stopwatch.java"

Python/Heap_sort.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#423
=> Revert "Heap_Sort"

Operation/Div.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#396
=> Revert "Div.py"

Operation/Mul.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#395
=> Revert "Mul.py"

Opration/Sum.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#392
=> Revert "Sum.py"

Python/Algorithms/isPrime.py
I added a function in python which returns True if the number the function received is prime, and False if the number is not prime.
=> Add isPrime Function in Python

Operation/Sub.py
Reverts aliya-rahmani/-HACKTOBERFEST2K20#394
=> Revert "Sub.py"

Python/blockchain/simple_blockchain.py
Reverts aliya-rahmani/Projects#445
=> Revert "Revert "Blockchain""

Python/instabot.py
Reverts aliya-rahmani/Projects#307
=>  "Delete instabot.py"

Bash/tvb.sh
Reverts aliya-rahmani/Projects#446
=> Revert "Revert "Create tvb.sh""

Python/debt_calculator.py, Python/money_calculator.py
Reverts aliya-rahmani/Projects#413
=> Revert "Debt calculator in python"

Python/Algorithms/BubbleSort.py
Reverts aliya-rahmani/Projects#429
=> Revert "Updated Bubble Sort.py"

Python/Read Excel File/excel_file.py
Reverts aliya-rahmani/Projects#406
=> Revert "Read excel with pandas example"

Python/wifi_password/rm
Reverts aliya-rahmani/Projects#521
=> Revert "Revert "Added two py files (Calculator.py and wifi_password.py)""

Opration/Sum.py
Reverts aliya-rahmani/Projects#520
=> Revert "Revert "Sum.py""

random_joke.py
Prints out different jokes related to programming from a free API in different colours.
=> Added random_joke.py
